version: '3'
services:
  # MySql
  word-mysql:
    image: mysql:5.6
    ports:
    - "3307:3306"
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: word
    networks:
    - fdse-network

  user-mysql:
    image: mysql:5.6
    ports:
    - "3308:3306"
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user
    networks:
    - fdse-network

  # serviceApi
  word-service:
    build: word-service
    image: leaveword-microservice/word-serviceApi
    restart: always
    depends_on:
    - word-mysql
    ports:
    - 8081:8081
    networks:
    - fdse-network

  user-service:
    build: user-service
    image: leaveword-microservice/user-serviceApi
    restart: always
    depends_on:
    - user-mysql
    ports:
    - 8082:8081
    networks:
    - fdse-network

networks:
  fdse-network:
    driver: bridge