version: '3'
services:
  # MySql数据库
  leaveword-mysql:
    image: mysql:5.6
    ports:
    - "3307:3306"
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: leaveword
    volumes:
      - ./mysql/config/mysql.cnf:/etc/my.cnf
      - ./mysql/mysql_data:/var/lib/mysql
    networks:
    - fdse-network

  word-service:
    build: word-service
    image: leaveword-microservice/word-service
    restart: always
    depends_on:
    - leaveword-mysql
    ports:
    - 8081:8081
    networks:
    - fdse-network

networks:
  fdse-network:
    driver: bridge