version: '3'
services:
  # MySql
  word-mysql:
    image: mysql:5.6
    ports:
    - "3307:3306"
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: word
    volumes:
    - ./word-mysql/config/mysql.cnf:/etc/my.cnf
    - ./word-mysql/mysql_data:/var/lib/mysql
    networks:
    - fdse-network

  user-mysql:
    image: mysql:5.6
    ports:
    - "3308:3306"
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user
    volumes:
    - ./user-mysql/config/mysql.cnf:/etc/my.cnf
    - ./user-mysql/mysql_data:/var/lib/mysql
    networks:
    - fdse-network

  # service
  word-service:
    build: word-service
    image: leaveword-microservice/word-service
    restart: always
    depends_on:
    - word-mysql
    ports:
    - 8081:8081
    networks:
    - fdse-network

  user-service:
    build: user-service
    image: leaveword-microservice/user-service
    restart: always
    depends_on:
    - user-mysql
    ports:
    - 8082:8081
    networks:
    - fdse-network

  login-service:
    build: login-service
    image: leaveword-microservice/login-service
    restart: always
    depends_on:
    - user-service
    ports:
    - 8083:8081
    networks:
    - fdse-network

  leaveword-ui:
    build: leaveword-ui
    image: leaveword-microservice/leaveword-ui
    restart: always
    ports:
      - 80:8080
    networks:
      - fdse-network

  register-service:
    build: register-service
    image: leaveword-microservice/register-service
    restart: always
    depends_on:
    - user-service
    ports:
    - 8083:8081
    networks:
    - fdse-network

networks:
  fdse-network:
    driver: bridge